image:
  name: python:3.6.8
  entrypoint: [""]

before_script:
  - pip install --upgrade pip && pip install "poetry==1.0.0" && poetry config virtualenvs.create false

stages:
  - check
  - test
  - publish

include:
  - project: continuous-integration/templates
    file: "/v1/version.yml"
  - project: continuous-integration/templates
    file: "/v1/commitlint.yml"
  - project: continuous-integration/templates
    file: '/v1/changelog.yml'

check:python:
  stage: check
  script:
    - make install
    - make lint
    - make test
  coverage: /Total coverage:\s([0-9.]+%)/
  artifacts:
    paths:
      - htmlcov/
