# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python Checks

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Installing Poetry 1.0.10
      uses: Gr1N/setup-poetry@v3
      with:
        poetry-version: 1.0.10
    - name: Installing dependencies
      run: make install
    - name: Linting
      run: make lint
    - name: Unit testing
      run: make test
